spring.application.name=telusko-app-client

spring.ai.openai.api-key=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
spring.ai.mcp.client.sse.connections.news.url=http://localhost:8481
spring.ai.mcp.client.sse.connections.math.url=http://localhost:8482
spring.ai.mcp.client.sse.connections.datetime.url=http://localhost:8483

spring.ai.mcp.client.toolcallback.enabled=false

logging.level.org.springframework.ai.mcp=INFO

