spring.application.name=mcp-app-1
spring.ai.openai.api-key=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
spring.ai.mcp.client.sse.connections.mcp-server.url=http://localhost:8484
spring.ai.mcp.client.stdio.servers-configuration=classpath:mcp-servers.json

